name: 'proto api docs'
description: 'Generate swagger api docs from protobuf & push them to a s3 bucket'
inputs:
  GIT_TOKEN:
    description: 'git token to use for clone protobuf repository'
    required: true
  GIT_URL:
    description: 'git repo url'
    required: true
  PROTO_BRANCH:
    description: 'branch to clone'
    required: true
  MODULE_LIST_FILE_PATH:
    description: 'path to file containing module list of protos to checkout'
    required: true
  AWS_S3_BUCKET:
    description: 's3 bucket name'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'aws access key id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'aws access key secret'
    required: true
  AWS_REGION:
    description: 'aws region'
    required: true
  SOURCE_DIR:
    description: 'source directory'
    required: true
  DEST_DIR:
    description: 'destination directory'
    required: true
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
      - ${{ inputs.GIT_TOKEN }}
        ${{ inputs.GIT_URL }}
        ${{ inputs.PROTO_BRANCH }}
        ${{ inputs.MODULE_LIST_FILE_PATH }}
        ${{ inputs.AWS_S3_BUCKET}}
        ${{ inputs.AWS_ACCESS_KEY_ID}}
        ${{ inputs.AWS_SECRET_ACCESS_KEY}}
        ${{ inputs.AWS_REGION}}
        ${{ inputs.SOURCE_DIR}}
        ${{ inputs.DEST_DIR}}
